"""empty message

Revision ID: fa9be3f0eb68
Revises: a5feb0ec3819
Create Date: 2019-05-28 10:37:27.981487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9be3f0eb68'
down_revision = 'a5feb0ec3819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hide_tracking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hide_tracking')
    # ### end Alembic commands ###
